install-wasi-target:
    rustup target add wasm32-wasip2

build mode="debug": install-wasi-target
    cargo build --target wasm32-wasip2 {{ if mode == "release" { "--release" } else { "" } }}
    python3 ../../scripts/name-component.py . target/wasm32-wasip2/{{ mode }}/context7.wasm
