[package]
name = "policy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
policy-mcp = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"
