[package]
name = "policy"
version = "0.1.0"
edition = "2021"
license.workspace = true


[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
serde_yaml = "0.9.33"

[dev-dependencies]
tempfile = "3.8"
