<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsComponentizeDotNet>true</IsComponentizeDotNet>
    <TargetName>get-open-meteo-weather-dotnet</TargetName>
  </PropertyGroup>

  <ItemGroup>
    <Wit Remove="**\*.wit" />
    <Wit Include="wit" World="get-open-meteo-weather-dotnet" />
  </ItemGroup>
</Project>
