<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsComponentizeDotNet>true</IsComponentizeDotNet>
    <TargetName>context7-dotnet</TargetName>
  </PropertyGroup>

  <ItemGroup>
    <Wit Remove="**\*.wit" />
    <Wit Include="wit" World="context7-dotnet" />
  </ItemGroup>
</Project>
