package microsoft:get-open-meteo-weather-dotnet;

/// Weather information services using the public Open-Meteo API.
world get-open-meteo-weather-dotnet {
    import wasi:http/outgoing-handler@0.2.1;

    /// Get current weather information for a specified city.
    export get-weather: func(city: string) -> result<string, string>;
}
