// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

use std::path::Path;
use std::{env, fs};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("prompt_templates.rs");

    // Read the markdown template files
    let rust_template =
        fs::read_to_string("prompts/rust-component.md").expect("Failed to read rust-component.md");
    let javascript_template = fs::read_to_string("prompts/javascript-component.md")
        .expect("Failed to read javascript-component.md");

    // Generate Rust code that includes the templates as constants
    let generated_code = format!(
        "// Auto-generated by build.rs - DO NOT EDIT\npub const RUST_COMPONENT_TEMPLATE: &str = r###\"{}\"###;\npub const JAVASCRIPT_COMPONENT_TEMPLATE: &str = r###\"{}\"###;\n",
        rust_template, javascript_template
    );

    fs::write(&dest_path, generated_code).expect("Failed to write prompt_templates.rs");

    // Rebuild if the template files change
    println!("cargo:rerun-if-changed=prompts/rust-component.md");
    println!("cargo:rerun-if-changed=prompts/javascript-component.md");
}
